config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'country/all_states'

  get 'country/top_five_pop'

  get 'country/top_five_area'

  resources :states
  root 'inventory#all_products'

  get 'one_product' => 'inventory#one_product'

  get 'by_category' => 'inventory#by_category'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/country_controller.rb
class CountryController < ApplicationController
  def all_states
  	@states = State.all
  end

  def top_five_pop
  	@states = State.order(:population).reverse_order.limit(5)
  end

  def top_five_area
  	@states = State.order(:area).reverse_order.limit(5)
  end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def all_products
  	@all = Product.all
  end

  def one_product
  	@one = Product.where(name: params[:name])
  end

  def by_category
  	@categories = Product.where(category: params[:category])
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :capitol, :population, :area)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/inventory/all_products.html.erb
<h1>Welcome to the Very Good Furniture Store</h1>
	<p>
		Come see us for your furniture needs. Or do not. I am not a beggar.
	</p>
	<small>End of commercial.</small>
	<br>

<h2>All Products</h2>


<ul>
	<% @all.each do |p| %>
		<li>
		<%= link_to p.name, one_product_path(name: p.name) %>
		<%= "$#{p.price}0" %>
		<%= link_to p.category, by_category_path(category: p.category) %>
		</li>
	<% end %>
</ul>

app/views/inventory/by_category.html.erb
<h1>Products in <%= params[:category] %></h1>

<p>"I made my first chair when I was five, but the quality was wanting, so when I turned nine, I used my factory wages to purchase some beautiful local walnut."</p>

<ul>
	<% @categories.each do |c| %>
		<li>
		<%= "#{c.name}, $#{c.price}0" %>
		</li>
	<% end %>
</ul>
<br>
<%= link_to "Back To All Products", root_path %>

app/views/inventory/one_product.html.erb
<h1><%= params[:name] %></h1>

<p>
<% @one.each do |n| %>
	<%= "Price: $#{n.price}0, Category: #{n.category}" %>
	<% end %>
</p>
<br>
<%= link_to "Back To All Products", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
		<meta charset=""utf-8"">
    <meta http-equiv=""X-UA-Compatible"" content=""IE=edge"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1"">
  <title>VeryGoodFurniture</title>
  <link href='https://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Very Good Furniture</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">States <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All States", country_all_states_path %></li>
            <li><%= link_to "Top 5 By Population", country_top_five_pop_path %></li>
            <li><%= link_to "Top 5 By Area", country_top_five_area_path %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<div class="container">
<%= yield %>
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>